[tool.poetry]
name = "foreign-born-p"
version = "0.1.0"
description = ""
authors = ["IsaiasZc <coroxerox2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.2"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
